# Generated by Django 4.2.19 on 2025-02-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.JSONField(default=dict),
        ),
    ]
