# Generated by Django 4.2.19 on 2025-02-12 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_dish_remove_order_items_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
    ]
